### ISSUE TITLE
Ability to sign TXs offline

### ISSUE THREAD

**Issue by JeremyParish69** [notional-labs/cosmoshub-legacy-multisig#11]
Requesting the ability to sign TXs offline, which I believe will require a sequence number override

Example:
![image](https://user-images.githubusercontent.com/95667791/163041291-b65e6e36-b1de-4e3c-bb19-aa29d9f2d075.png)

**Comment by sontrinh16** [comment]
Hey there, we are currently working on multisig-ui on a different repo and i believe we have solved this issue.

New repo link:
[https://github.com/notional-labs/multisig-ui](url)

**Comment by sontrinh16** [comment]
for more issues please add it in the newly provided repo
